In [1]:
import os
print(os.listdir())

['Untitled1.ipynb', '.ipynb_checkpoints', 'Activity_ Strings.ipynb', 'Untitled.ipynb', 'all_trips_sample_2025.csv', 'Exemplar_ Strings.ipynb']

In [2]:
import pandas as pd
df = pd.read_csv("all_trips_sample_2025.csv")

In [3]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length_minutes,day_of_week,month,hour,day_name
0,AD14E156C7397848,electric_bike,2025-05-18 00:14:34.731000 UTC,2025-05-18 00:18:24.066000 UTC,Hegewisch Metra Station,20215,Commercial Ave & 130th St,20213,41.648501,-87.546090,41.659150,-87.550762,casual,3,1,5,0,Sunday
1,3EE85DDAF9F21532,electric_bike,2025-11-27 23:18:05.740000 UTC,2025-11-27 23:25:15.510000 UTC,NaN,NaN,Hegewisch Metra Station,CHI00876,41.650000,-87.530000,41.648501,-87.546090,casual,7,5,11,23,Thursday
2,AF4CD368E02BA0C3,classic_bike,2025-05-27 20:15:18.719000 UTC,2025-05-27 20:24:28.810000 UTC,Avenue O & 134th St,20214,Avenue O & 134th St,20214,41.651903,-87.539555,41.651903,-87.539555,casual,9,3,5,20,Tuesday
3,A6AB143C36A992B4,classic_bike,2025-02-22 13:25:13.396000 UTC,2025-02-22 13:37:39.655000 UTC,Avenue O & 134th St,20214,Torrence Ave & 126th Pl,20217,41.651903,-87.539555,41.666312,-87.557216,member,12,7,2,13,Saturday
4,9583CE245F6BA01F,electric_bike,2025-08-24 12:36:26.484000 UTC,2025-08-24 13:35:28.882000 UTC,Avenue O & 134th St,CHI00843,Avenue O & 134th St,CHI00843,41.651905,-87.539568,41.651903,-87.539555,casual,59,1,8,12,Sunday

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37114 entries, 0 to 37113
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ride_id              37114 non-null  object
 1   rideable_type        37114 non-null  object
 2   started_at           37114 non-null  object
 3   ended_at             37114 non-null  object
 4   start_station_name   28316 non-null  object
 5   start_station_id     28316 non-null  object
 6   end_station_name     28055 non-null  object
 7   end_station_id       28055 non-null  object
 8   start_lat            37114 non-null  float64
 9   start_lng            37114 non-null  float64
 10  end_lat              37114 non-null  float64
 11  end_lng              37114 non-null  float64
 12  member_casual        37114 non-null  object
 13  ride_length_minutes  37114 non-null  int64
 14  day_of_week          37114 non-null  int64
 15  month                37114 non-null  int64
 16  hour                 37114 non-null  int64
 17  day_name             37114 non-null  object
dtypes: float64(4), int64(4), object(10)
memory usage: 5.1+ MB

In [5]:
df.shape

(37114, 18)

In [7]:
df.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name     8798
start_station_id       8798
end_station_name       9059
end_station_id         9059
start_lat                 0
start_lng                 0
end_lat                   0
end_lng                   0
member_casual             0
ride_length_minutes       0
day_of_week               0
month                     0
hour                      0
day_name                  0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.describe()

,start_lat,start_lng,end_lat,end_lng,ride_length_minutes,day_of_week,month,hour
count,37114.000000,37114.000000,37114.000000,37114.000000,37114.000000,37114.000000,37114.000000,37114.000000
mean,41.829140,-87.639815,41.834257,-87.636841,14.302716,4.091664,6.964407,13.783613
std,0.065148,0.058200,0.065914,0.053634,32.068895,1.981934,2.829884,4.927413
min,41.648501,-87.860000,41.640000,-87.870000,0.000000,1.000000,1.000000,0.000000
25%,41.787878,-87.696730,41.790000,-87.670000,4.000000,2.000000,5.000000,10.000000
50%,41.800000,-87.613533,41.802406,-87.617930,7.000000,4.000000,7.000000,14.000000
75%,41.851375,-87.598906,41.879255,-87.599861,16.000000,6.000000,9.000000,17.000000
max,42.070000,-87.520000,42.070000,-87.510000,1499.000000,7.000000,12.000000,23.000000

In [10]:
df.["member_casual"].value_counts()

SyntaxError: invalid syntax (<ipython-input-10-e3b9aa47f5f4>, line 1)

In [11]:
df["member_casual"].value_counts()

member    23684
casual    13430
Name: member_casual, dtype: int64

In [12]:
df["member_casual"].value_counts(normalize=True) * 100

member    63.814194
casual    36.185806
Name: member_casual, dtype: float64

In [13]:
df.groupby("member_casual")["ride_length_minutes"].mean()

member_casual
casual    18.731348
member    11.791463
Name: ride_length_minutes, dtype: float64

In [14]:
df.groupby(["day_name", "member_casual"])["ride_id"].count()

day_name   member_casual
Friday     casual           2170
           member           3701
Monday     casual           1651
           member           3384
Saturday   casual           2333
           member           3034
Sunday     casual           2171
           member           2628
Thursday   casual           1871
           member           3630
Tuesday    casual           1675
           member           3800
Wednesday  casual           1559
           member           3507
Name: ride_id, dtype: int64

In [15]:
df.groupby(["month", "member_casual"])["ride_id"].count()

month  member_casual
1      casual            273
       member           1001
2      casual            315
       member           1083
3      casual            682
       member           1604
4      casual            928
       member           2259
5      casual           1366
       member           2302
6      casual           1650
       member           2126
7      casual           1954
       member           2482
8      casual           1843
       member           2362
9      casual           1763
       member           2612
10     casual           1617
       member           3201
11     casual            781
       member           1953
12     casual            258
       member            699
Name: ride_id, dtype: int64

In [16]:
df.groupby(["hour", "member_casual"])["ride_id"].count()

hour  member_casual
0     casual            319
      member            214
1     casual            216
      member            128
2     casual            138
      member             87
3     casual            101
      member             78
4     casual             89
      member             71
5     casual            119
      member            182
6     casual            236
      member            452
7     casual            337
      member            887
8     casual            460
      member           1374
9     casual            620
      member           1415
10    casual            693
      member           1307
11    casual            744
      member           1349
12    casual            901
      member           1585
13    casual            891
      member           1627
14    casual            978
      member           1533
15    casual           1036
      member           1744
16    casual           1059
      member           1978
17    casual           1054
      member           2089
18    casual            959
      member           1734
19    casual            797
      member           1332
20    casual            540
      member            923
21    casual            444
      member            715
22    casual            359
      member            542
23    casual            340
      member            338
Name: ride_id, dtype: int64

In [17]:
df.groupby(["rideable_type", "member_casual"])["ride_id"].count()

rideable_type  member_casual
classic_bike   casual            4319
               member            8863
electric_bike  casual            9111
               member           14821
Name: ride_id, dtype: int64

In [18]:
summary = (
    df.groupby("member_casual")
    .agg(
        total_rides=("ride_id", "count"),
        average_duration=("ride_length_minutes", "mean")
    )
    .round(2)
)
summary

               total_rides  average_duration
member_casual
casual               13430             18.73
member               23684             11.79

In [20]:
summary.to_csv("summary_rides.csv")

In [21]:
import os

os.listdir()

['Untitled1.ipynb',
 '.ipynb_checkpoints',
 'Activity_ Strings.ipynb',
 'summary_rides.csv',
 'Untitled.ipynb',
 'all_trips_sample_2025.csv',
 'Exemplar_ Strings.ipynb']